[target.x86_64-pc-windows-msvc]
rustflags = [
    "-Zlocation-detail=none",
]
[target.wasm32-unknown-emscripten]
rustflags = [

    "-Zlocation-detail=none",
    "-C", "link-args=-sSIDE_MODULE=2",
    "-C", "link-args=-pthread", # was -sUSE_PTHREADS=1 in earlier emscripten versions
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-Zlink-native-libraries=no"
]